platformName=android
platformVersion=15
deviceName=TrueCaller
appPackage=com.truecaller
appActivity=com.truecaller.ui.TruecallerInit
udid=emulator-5554
phoneNumber_firstAttempt= 123456789
phoneNumber_secondAttempt= 987654321
country = Congo
