## RANDOM PROPERTIES
platformName=android
platformVersion=15
deviceName=TrueCaller
appPackage=com.qatestapp
appActivity=com.qatestapp.RegistrationScreen
udid=RF123456SRLSY
username=helloworld@gmail.com
password=testing1234
